#
# System dependent settings
#
# $Id: make.inc 1123 2006-09-06 12:14:56Z valcke $
#
##### User configurable options #####
#
# Note: The absolute path name must be indicated.
#
# Note: Choose one of these includes files and modify it according to your
#       local settings. Replace the currently active file with your own.
#
include path_to_models_directory/oasis3-mct_$(version_oasis)/util/make_dir/make.$(machine)
#
### End User configurable options ###
